using EllahColNum.Core.Text;

namespace EllahColNum.Core.Models;

/// <summary>
/// Represents a group of column elements that share the same X,Y position.
/// A multi-floor column (e.g. floor 1 to floor 5) appears as one group.
/// A new column starting on floor 3 at a different position is a separate group.
/// </summary>
public class ColumnGroup
{
    /// <summary>Unique key for this position (generated by ColumnGrouper)</summary>
    public string Key { get; set; } = "";

    /// <summary>All column elements belonging to this position</summary>
    public List<ColumnData> Columns { get; set; } = [];

    /// <summary>Representative X coordinate for sorting</summary>
    public double X => Columns.Count > 0 ? Columns[0].X : 0;

    /// <summary>Representative Y coordinate for sorting</summary>
    public double Y => Columns.Count > 0 ? Columns[0].Y : 0;

    /// <summary>
    /// Parsed grid name (e.g. "A" from "A(64)-1(-46)").
    /// Used for grid-based numbering mode.
    /// </summary>
    public string GridRow { get; set; } = "";

    /// <summary>
    /// Parsed grid name (e.g. "1" from "A(64)-1(-46)").
    /// Used for grid-based numbering mode.
    /// </summary>
    public string GridColumn { get; set; } = "";

    /// <summary>The mark that will be assigned to all columns in this group</summary>
    public string AssignedMark { get; set; } = "";

    /// <summary>Existing mark detected from current Revit data (if any)</summary>
    public string? ExistingMark { get; set; }

    /// <summary>Classification set by MarkAnalyzer</summary>
    public GroupNumberingStatus NumberingStatus { get; set; } = GroupNumberingStatus.NotNumbered;

    /// <summary>How many floors this column group spans</summary>
    public int FloorCount => Columns.Count;

    /// <summary>
    /// Returns the column whose BaseLevelName matches the given level name,
    /// or null if no column at that floor exists in this group.
    /// Used by NumberingEngine to anchor sort positions to a reference floor.
    /// </summary>
    public ColumnData? GetColumnAtFloor(string levelName)
    {
        if (string.IsNullOrWhiteSpace(levelName)) return null;
        // BiDi-tolerant comparison so Hebrew level names match across the
        // boundaries of separate Revit API calls (which may differ by invisible
        // RTL marks).  See BidiText for the full set of stripped controls.
        return Columns.FirstOrDefault(c =>
            BidiText.EqualsIgnoreBidi(c.BaseLevelName, levelName) ||
            BidiText.EqualsIgnoreBidi(c.TopLevelName,  levelName));
    }
}

public enum GroupNumberingStatus
{
    /// <summary>No columns in this group have a Mark</summary>
    NotNumbered,

    /// <summary>All columns share the same Mark — keep it</summary>
    FullyNumbered,

    /// <summary>Some floors have a Mark, some don't — complete it</summary>
    PartiallyNumbered,

    /// <summary>Different floors have different Marks — warn user</summary>
    Conflicting,
}
